import enum


class PacketID(enum.IntEnum):
    MOTION = 0
    SESSION = 1
    LAP_DATA = 2
    EVENT = 3
    PARTICIPANTS = 4
    CAR_SETUPS = 5
    CAR_TELEMETRY = 6
    CAR_STATUS = 7
    FINAL_CLASSIFICATION = 8
    LOBBY_INFO = 9
    CAR_DAMAGE = 10
    SESSION_HISTORY = 11
    TYRE_SETS = 12
    MOTION_EX = 13
    TIME_TRIAL = 14
    LAP_POSITIONS = 15
    CAR_TELEMETRY_2 = 16


MAX_CARS = 24
MAX_PARTICIPANT_NAME_LEN = 32
MAX_TYRE_STINTS = 8
MAX_NUM_TYRE_SETS = 13 + 7  # 13 slick + 7 wet weather

MAX_MARSHAL_ZONES_PER_LAP = 21
MAX_ACTIVE_AERO_ZONES_PER_LAP = 8
MAX_DRS_ZONES_PER_LAP = 4
MAX_WEATHER_FORECAST_SAMPLES = 64
MAX_SESSIONS_IN_WEEKEND = 12

EVENT_STRING_CODE_LEN = 4

MAX_LAPS_IN_HISTORY = 100

MAX_LAPS_IN_LAP_POSITIONS_HISTORY = 50
